spring:
    application:
        name: future-project
    profiles:
        active: @deploy.type@
    main:
        allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            indent-output: false
            fail-on-empty-beans: false # 允许序列化无属性的Bean
    servlet:
        multipart:
            max-file-size: 16MB
            max-request-size: 32MB
# mybatis plus 相关配置
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下
    global-config:
        db-config:
            id-type: NONE # “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
#            id-type: AUTO # 自增 ID，适合 MySQL 等直接自增的数据库
#            id-type: INPUT # 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
#            id-type: ASSIGN_ID # 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
            logic-delete-value: 1 # 逻辑已删除值(默认为 1)
            logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    type-aliases-package: com.future
