server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.0.4.9:3306/future?useUnicode=true&characterEncoding=utf8&autoReconnect=true
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
framework:
    cors: true
    jwt:
        duration: 30m
        secret: future