spring:
    profiles:
        active: @deploy.type@
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            indent-output: false
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: com.future.framework.jpa.CustomDialect
    datasource:
        druid:
            url: 